<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Arch" />
    <PackageReference Include="Silk.NET.Maths" />
    <PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
</Project>
